/**
 * Auto-generated AppRouter type from web-app
 * This file is generated by importing from the web-app tRPC router
 */

// Import the AppRouter type directly from the web-app
export type { AppRouter } from '../../../web-app/lib/trpc/root';

// Re-export the schemas for convenience
export {
  signupSchema,
  loginSchema,
  userSchema
} from '../../../web-app/lib/trpc/routers/auth';

// Re-export the inferred types
import type { z } from 'zod';
import { signupSchema, loginSchema, userSchema } from '../../../web-app/lib/trpc/routers/auth';

export type User = z.infer<typeof userSchema>;
export type SignupInput = z.infer<typeof signupSchema>;
export type LoginInput = z.infer<typeof loginSchema>;
